// This file is automatically generated. Do not edit it directly.
import HeroSection from "@/components/HeroSection";
import HowItWorksSection from "@/components/HowItWorksSection";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Wizard from "@/components/Wizard";
import StyleGallerySection from "@/components/StyleGallerySection";
import TestimonialsSection from "@/components/TestimonialsSection";
import FaqSection from "@/components/FaqSection";

const Index = () => {
  return (
    <div className="min-h-screen flex flex-col bg-lavender/10">
      <Header />
      <main className="flex-grow">
        <HeroSection />
        <div className="container mx-auto px-4 py-16" id="wizard">
          <Wizard />
        </div>
        <HowItWorksSection />
        <StyleGallerySection />
        <TestimonialsSection />
        <FaqSection />
      </main>
      <Footer />
    </div>
  );
};

export default Index;
