
// This file is automatically generated. Do not edit it directly.
import { Link } from "react-router-dom";
import { AuthButtons } from "./AuthButtons";

const Header = () => {
  return (
    <header className="bg-white shadow-sm">
      <div className="container mx-auto px-4 py-4 flex justify-between items-center">
        <Link to="/" className="text-2xl font-bold text-persimmon font-fredoka">StoryBloom</Link>
        <AuthButtons />
      </div>
    </header>
  );
};

export default Header;
