// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjgzqgpfqztkgggxxqkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZ3pxZ3BmcXp0a2dnZ3h4cWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjc4OTMsImV4cCI6MjA2MTcwMzg5M30.vuBfmpdanQJ7CUkEu8kd6C-PUdCLow6tinfvIt3O7Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);