// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_CONFIG } from './config';

console.log('Creating Supabase client with:', SUPABASE_CONFIG.url, SUPABASE_CONFIG.anonKey);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_CONFIG.url,
  SUPABASE_CONFIG.anonKey
);

// Create a service role client for admin operations
export const supabaseAdmin = createClient<Database>(
  SUPABASE_CONFIG.url,
  SUPABASE_CONFIG.serviceRoleKey
);